[package]
name="doom_app"
version="0.1.0"
edition="2021"
description="Application base for Doom-rs"
publish = false

[dependencies]
glutin={version="0.30"}
glutin-winit="0.2"
winit="0.27"
raw-window-handle="0.5"