[package]
name = "kabal_render"
version = "0.1.0"
edition = "2021"
description = "Render code for Kabal engine"
publish = false
build = "build.rs"

[dependencies]
cgmath = "0.18"
glutin = "0.31"

[build-dependencies]
gl_generator = "0.14"
